version: '3.8'

services:
  blocking_server:
    build:
      context: .
    ports:
      - "8081:8080"
    command: ./blocking_server

  nonblocking_server:
    build:
      context: .
    ports:
      - "8082:8080"
    command: ./nonblocking_server

  blocking_client:
    build:
      context: .
    depends_on:
      - blocking_server
      - nonblocking_server
    command: ./blocking_client

  nonblocking_client:
    build:
      context: .
    depends_on:
      - blocking_server
      - nonblocking_server
    command: ./nonblocking_client
